export const data = {
    products: [
        {
            _id: '1',
            name: 'Remera básica',
            category: 'Remeras',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Buenarda',
            rating: 4.5,
            numReviews: 10,
            countInStock: 16,
        },
        {
            _id: '2',
            name: 'Buzo básico',
            category: 'Buzos',
            image: '/images/product-2.jpg',
            price: 100,
            brand: 'Kamikaze',
            rating: 5,
            numReviews: 8,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Pantalon Jogging',
            category: 'Pantalones',
            image: '/images/product-3.jpg',
            price: 105,
            brand: 'Epico',
            rating: 4,
            numReviews: 12,
            countInStock: 20,
        },
        {
            _id: '4',
            name: 'Gorra lisa',
            category: 'Gorras',
            image: '/images/product-4.jpg',
            price: 125,
            brand: 'SoftCore',
            rating: 4.5,
            numReviews: 14,
            countInStock: 0,
        },
        {
            _id: '5',
            name: 'Zapatillas deportivas',
            category: 'Zapatillas',
            image: '/images/product-5.jpg',
            price: 600,
            brand: 'Nikeeee',
            rating: 5,
            numReviews: 23,
            countInStock: 18,
        },
        {
            _id: '6',
            name: 'Medias deportivas',
            category: 'Medias',
            image: '/images/product-6.jpg',
            price: 25,
            brand: 'Tumai',
            rating: 3,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '7',
            name: 'Medias deportivas color negro',
            category: 'Medias',
            image: '/images/product-7.jpg',
            price: 26,
            brand: 'Tumai',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
        },
        {
            _id: '8',
            name: 'Pantalon Jogging gris',
            category: 'Pantalones',
            image: '/images/product-8.jpg',
            price: 135,
            brand: 'Epico',
            rating: 5,
            numReviews: 17,
            countInStock: 29,
        },
        {
            _id: '9',
            name: 'Pantalon Jogging azul',
            category: 'Pantalones',
            image: '/images/product-9.jpg',
            price: 165,
            brand: 'Seronio',
            rating: 4,
            numReviews: 13,
            countInStock: 14,
        },

    ],
};